# Generated by Django 3.2.4 on 2021-06-23 17:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_name', models.TextField()),
                ('door_number', models.PositiveIntegerField()),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
    ]
# address_3 = addressbook(name ='Pacific Oceanic',street_name = 'Honeycomb Street', door_number= 67,postcode= 'B12 5LQ')



